# Pre-commit configuration for Carbon Guard CLI
repos:
  # Built-in pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.md$'
      - id: end-of-file-fixer
        exclude: '\.json$'
      - id: check-yaml
        args: ['--unsafe']
      - id: check-json
        exclude: 'test.*\.json$|.*results\.json$|moto.*\.json$'
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: requirements-txt-fixer

  # Python code formatting with Black
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        args: ['--line-length=88']
        exclude: '^(venv/|\.venv/|build/|dist/|__pycache__/)'

  # Import sorting with isort
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ['--profile=black', '--line-length=88']
        exclude: '^(venv/|\.venv/|build/|dist/|__pycache__/)'

  # Remove unused imports
  - repo: https://github.com/pycqa/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args:
          - '--in-place'
          - '--remove-all-unused-imports'
          - '--remove-unused-variables'
          - '--remove-duplicate-keys'
        exclude: '^(venv/|\.venv/|build/|dist/|__pycache__/)'

# Configuration
default_language_version:
  python: python3

# Global excludes
exclude: |
  (?x)^(
      venv/.*|
      \.venv/.*|
      build/.*|
      dist/.*|
      \.git/.*|
      __pycache__/.*|
      \.pytest_cache/.*|
      .*\.egg-info/.*|
      \.history/.*|
      boto3_ec2_co2_example\.py.*
  )$

# Don't fail fast - show all issues
fail_fast: false
